### ISSUE TITLE
Bug: Character Slots Filled With Bugged Amulets

### ISSUE THREAD

**Issue by 0utrider** [Truinto/KingmakerFumi#1]
Hi there,
I was enjoying the mod, thanks for some much-needed variety to the Kineticist!

It seems after one of the most recent patches, this mod now bugs the game for me. Current games won't load, and new games do this:
[Screenshot](https://i.imgur.com/Yw3xTJa.png)

I spent some time experimenting with various mods removed and narrowed it down to this one. It seems to have the problem when installed alongside other mods, but I haven't been able to narrow down which one. Here is my list:

**ATouchOfMagic**   _<--- this is the conflicting mod_
BagOfTricks
BetterVendors
CallOfTheWild
CombatRoundLogger
CommunityPatch
CraftMagicItems
HighlightLearnableScrolls
KingmakerBuffBot
QuickUse
RacesUnleashed
RemoveAreaEffects
Respec
TheLootChecklist
thelostgrimoire
TurnBased
UIExtensions
VisualAdjustments
ZFavoredClass

**~~EDIT:** After some further testing, it seems to be ATouchOfMagic that is creating the problem. With that mod removed, this mod works fine. I'll see about letting that author know as well.

The problem persists if you only use ATouchOfMagic, CallOfTheWild, and Fumi's. Removing that, to where your mods only consist of CallOfTheWild and Fumi's, gets things working again.

**Comment by Truinto** [comment]
That's a really strange bug. I cannot think for any reason for why that would happen. I assume you did test CotW with ATouchOfMagic without my mod, right? I know that CotW had a lot of recent updates, so maybe some new bug popped up.

**Comment by Truinto** [comment]
Could not confirm; missing info.
