### ISSUE TITLE
Witches' hexes target AC

### ISSUE THREAD

**Issue by Valorier** [Truinto/KingmakerFumi#2]
![image](https://user-images.githubusercontent.com/74416275/99083624-14f0a680-25c6-11eb-87fe-f999340009ca.png)
Hello,

As you can see in the file attached, witches' hexes target melee touch AC instead of forcing a saving throw. It seems linked with Hexstrike somehow.
This is, however, inconsistent, sometimes they do initiate a saving throw.

It is pretty crippling for witches. Tested with Winter witches and Hedge witches so far.

Thank you for your mod, and I hope it can be fixed !

**Comment by Truinto** [comment]
I am a bit late for the party. I will finally start debugging my mess :P
Still quite busy. Maybe you could playtest my preview: https://github.com/Truinto/KingmakerFumi/raw/master/testing/FumisCodex.dll

I changed:
## [1.0.9-preview]
- fixed mobile blast
- fixed accidentally making some hexes touch attacks
- fixed Impale triggering way too many 'Attacks of Opportunity'

**Comment by Truinto** [comment]
Fixed with a lot of other bugs.
