### ISSUE TITLE
Ki Leech doesn't restore Ki when reducing a living Target to 0 HP or less.

### ISSUE THREAD

**Issue by Skurrio** [Truinto/KingmakerFumi#7]
Greetings,

I tried Ki Leech on a Sensei Monk and a Zen Archer Monk and in both Cases they only gained Ki when they confirmed a Crit and never got Ki when reducing an Enemy to 0 HP or less.

Thank you for your great Work.

**Comment by Truinto** [comment]
Made a fix. If you use an attack with multiple projectiles, then only the last projectile is checked. This cannot be fixed, without heavy modification. So you are fine, as long as you don't use Multishoot.

The project settings are really old. I had to update quite a bit. Let me know, that the mod still works.
